const resPath = {
    couch: 'res/img/couch.png',
    desk: 'res/img/desk.png',
    fire: 'res/img/fire.png',
    fireAnimated: 'res/spritesheet/fire_animated.json',
    firePlace: 'res/img/fire_place.png',
    houseBackground: 'res/img/house_background.png',
    kitchen: 'res/img/kitchen.png',
    lightSwitchOn: 'res/img/light_switch_on.png',
    lightSwitchOff: 'res/img/light_switch_off.png',
    speaker: 'res/img/speakers.png',
    speakerAnimated: 'res/spritesheet/speaker_animated.json',
    rainAnimated: 'res/spritesheet/rain_animated.json',
    window: 'res/img/window.png',
    woodWall: 'res/img/wood_wall.jpg',
    lightOff: 'res/img/light_switch_off.png',
    lightOn: 'res/img/light_switch_on.png',
    scene: 'res/img/scene.png',
    frame: 'res/img/frame.png',
    picture: 'res/img/picture.png',
    lightning: 'res/img/lightning.png'
}