const resPath = {
    "baseboard": "res/img/baseboard.png",
    "couch": "res/img/couch.png",
    "desk": "res/img/desk.png",
    "fire": "res/img/fire.png",
    "fireAnimated": "res/spritesheet/fire_animated.json",
    "firePlace": "res/img/fire_place.png",
    "frame": "res/img/frame.png",
    "houseBackground": "res/img/house_background.png",
    "kitchen": "res/img/kitchen.png",
    "lightOff": "res/img/light_switch_off.png",
    "lightOn": "res/img/light_switch_on.png",
    "lightning": "res/img/lightning.png",   
    "lightSwitchOn": "res/img/light_switch_on.png",
    "lightSwitchOff": "res/img/light_switch_off.png",
    "rainAnimated": "res/spritesheet/rain_animated.json",
    "picture": "res/img/picture.png",
    "speaker": "res/img/speakers.png",
    "speakerAnimated": "res/spritesheet/speaker_animated.json",
    "scene": "res/img/scene.png",
    "wall0": "res/img/wall_texture_0.jpg",
    "wall1": "res/img/wall_texture_1.jpg",
    "wall2": "res/img/wall_texture_2.jpg",
    "wall3": "res/img/wall_texture_3.jpg",
    "wall4": "res/img/wall_texture_4.jpg",
    "wall5": "res/img/wall_texture_5.jpg",
    "window": "res/img/window.png"
}