const resPath = {
    "couch": "res/img/couch.png",
    "cameraImage": "res/img/camera_image.jpg",
    "fireAnimated": "res/spritesheet/fire_animated.json",
    "firePlace": "res/img/fire_place.png",
    "flashAnimated" : "res/spritesheet/flash_animated.json",
    "frame": "res/img/frame.png",
    "lightOff": "res/img/light_switch_off.png",
    "lightOn": "res/img/light_switch_on.png",
    "lightSwitchOn": "res/img/light_switch_on.png",
    "lightSwitchOff": "res/img/light_switch_off.png",
    "picture": "res/img/picture.png",
    "speaker": "res/img/speakers.png",
    "speakerAnimated": "res/spritesheet/speaker_animated.json",
    "speechBubble": "res/img/speechBubble.png",
    "wall0": "res/img/wall_texture_0.jpg",
    "wall1": "res/img/wall_texture_1.jpg",
    "wall2": "res/img/wall_texture_2.jpg",
    "wall3": "res/img/wall_texture_3.jpg",
    "wall4": "res/img/wall_texture_4.jpg",
    "wall5": "res/img/wall_texture_5.jpg",
    "window": "res/img/window.png"
}